#define LIFEV_HAS_CORE
#define LIFEV_HAS_ETA
/* #undef LIFEV_HAS_BCINTERFACE */
/* #undef LIFEV_HAS_ONEDFSI */
/* #undef LIFEV_HAS_ZERODIMENSIONAL */
/* #undef LIFEV_HAS_LEVELSET */
/* #undef LIFEV_HAS_DARCY */
#define LIFEV_HAS_NAVIERSTOKES
/* #undef LIFEV_HAS_NAVIERSTOKESBLOCKS */
#define LIFEV_HAS_ETA
/* #undef LIFEV_HAS_STRUCTURE */
/* #undef LIFEV_HAS_ELECTROPHYSIOLOGY */
/* #undef LIFEV_HAS_HEART */
/* #undef LIFEV_HAS_FSI */
/* #undef LIFEV_HAS_FSI_BLOCKS */
/* #undef LIFEV_HAS_MULTISCALE */
/* #undef LIFEV_HAS_DUMMY */
#define LIFEV_HAS_HIMOD
/* #undef H5_USE_16_API */
